name: Manual build 

on: 
  workflow_dispatch:
#    inputs:
#      PHASE_ID:
#        description: 'Phase Identifier (x, f, b or null)'
#        required: false
#        default: 'x'
#      TAG:
#        description: 'Tag (N/Y)'
#        required: true
#        default: 'N'
#      TAG_NAME:
#        description: 'Git Tag Name'
#        required: false
#        default: 'NOVOS_LIB_4.3.0'
env:
  DISPLAY_CONTEXT: ${{ secrets.DISPLAY_CONTEXT }} # To display github context for debugging

jobs:

  linux-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      PHASE_ID: x

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set branch name from github reference
        run: |
          BRANCH_NAME=`basename ${{ github.ref }}`
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Build the application
        working-directory: build
        run: |
          echo "Repo Owner:" ${{ github.repository_owner }}
          echo "Run ID:" ${{ github.run_id }}
          echo ${{ github.run_id }} > run_id-${{ env.BRANCH_NAME }}.txt

          export VER_NUM=`cat version.txt` 
          echo "${VER_NUM}${PHASE_ID}-${BUILD_NUMBER}" > version_num.txt
          #echo "${VER_NUM}${{ github.event.inputs.PHASE_ID }}-${BUILD_NUMBER}" > version_num.txt
          #PHASE_ID=${{ github.event.inputs.PHASE_ID }}
          echo "PHASE ID: ${PHASE_ID}"
          echo "BUILD NUMBER: ${BUILD_NUMBER}"
          echo "PHASE ID: ${{ github.event.inputs.PHASE_ID }}"
          cat version_num.txt
          bash bbuild.sh .. 

      - name: Upload version.txt artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: version-${{ env.BRANCH_NAME }}-txt
          retention-days: 14
          path: |
            build/version.txt

      - name: Upload version_num.txt artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: version-num-${{ env.BRANCH_NAME }}-txt
          retention-days: 14
          path: |
            build/version_num.txt

      - name: Upload run_id artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: run_id-${{ env.BRANCH_NAME }}.txt
          retention-days: 14
          path: |
            build/run_id-${{ env.BRANCH_NAME }}.txt

      - name: Dump context
        if: ${{ env.DISPLAY_CONTEXT == 'true' }}
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          JOB_CONTEXT: ${{ toJSON(job) }}
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: |
          echo "GITHUB CONTEXT:"
          echo
          echo "$GITHUB_CONTEXT"
          echo
          echo "JOB CONTEXT:"
          echo
          echo "$JOB_CONTEXT"
          echo
          echo "STEPS CONTEXT:"
          echo
          echo "$STEPS_CONTEXT"
